/* eslint-disable no-console */
// Signing and packaging contacts for Logbook of the World.
//
// WHAT THIS IS GUARDING AGAINST. A malformed field gets a readable complaint back from
// LoTW. A signature over the WRONG BYTES gets the whole file refused with no indication of
// which part was wrong, and there is no test server to try it against — so the only defence
// is to pin the exact signed string here. docs/lotw-upload.md previously recorded the order
// wrong (station callsign first, `YYYYMMDD` dates); the golden strings below are what stops
// that being reintroduced.
//
// The certificate is generated by this script with openssl, carrying the same subject OID
// and the same three extensions a real LoTW certificate carries. Nobody's licence identity
// is involved.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createVerify, X509Certificate } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";

import { certExtensionText, certInfoFromPem, readP12 } from "@/lib/integrations/lotw-cert";
import {
  buildTq8,
  lotwMode,
  mhz,
  signData,
  type LotwContact,
  type LotwStation,
} from "@/lib/integrations/lotw-tq8";
import { keysFromAdif } from "@/lib/integrations/lotw-reconcile";
import { readLotwReply, tq8Filename } from "@/lib/integrations/lotw-upload";

let pass = 0;
let fail = 0;
function ok(cond: boolean, label: string): void {
  if (cond) {
    pass++;
    console.log(`  ok    ${label}`);
  } else {
    fail++;
    console.log(`  FAIL  ${label}`);
  }
}
function eq(got: unknown, want: unknown, label: string): void {
  const good = got === want;
  if (!good) console.log(`        got  ${JSON.stringify(got)}\n        want ${JSON.stringify(want)}`);
  ok(good, label);
}

const CONF = `oid_section = new_oids
[new_oids]
lotwCall = 1.3.6.1.4.1.12348.1.1
[req]
distinguished_name = dn
x509_extensions = v3
prompt = no
[dn]
CN = Example Operator
lotwCall = K9XYZ
[v3]
1.3.6.1.4.1.12348.1.2 = ASN1:PRINTABLESTRING:19450101000000Z
1.3.6.1.4.1.12348.1.3 = ASN1:PRINTABLESTRING:20301231000000Z
1.3.6.1.4.1.12348.1.4 = ASN1:PRINTABLESTRING:291
`;

const dir = mkdtempSync(join(tmpdir(), "digishack-lotw-"));
let certPem = "";
let keyPem = "";
let p12: Buffer | null = null;

try {
  writeFileSync(join(dir, "o.cnf"), CONF);
  execFileSync(
    "openssl",
    // 2048 rather than a smaller key: RSA-SHA1 with a short key is refused outright by
    // OpenSSL 3, which would make a signing failure look like a format problem.
    ["req", "-x509", "-newkey", "rsa:2048", "-keyout", join(dir, "k.pem"), "-out",
     join(dir, "c.pem"), "-days", "3650", "-nodes", "-config", join(dir, "o.cnf")],
    { stdio: ["ignore", "ignore", "ignore"] },
  );
  execFileSync(
    "openssl",
    ["pkcs12", "-export", "-in", join(dir, "c.pem"), "-inkey", join(dir, "k.pem"),
     "-out", join(dir, "t.p12"), "-passout", "pass:"],
    { stdio: ["ignore", "ignore", "ignore"] },
  );
  certPem = readFileSync(join(dir, "c.pem"), "utf8");
  keyPem = readFileSync(join(dir, "k.pem"), "utf8");
  p12 = readFileSync(join(dir, "t.p12"));
} catch (err) {
  console.log(`  FAIL  openssl could not build a test certificate: ${String(err).slice(0, 200)}`);
  fail++;
}

// Wrapped because `readP12` is async and tsx builds these scripts as CJS, where a
// top-level await is a build error rather than a runtime one.
async function main(): Promise<void> {
console.log("reading a .p12");
if (p12) {
  const read = await readP12(p12, "");
  ok(read.certPem.includes("BEGIN CERTIFICATE"), "the certificate comes out");
  ok(/BEGIN (RSA )?PRIVATE KEY/.test(read.keyPem), "and the private key");
  eq(
    new X509Certificate(read.certPem).fingerprint256,
    new X509Certificate(certPem).fingerprint256,
    "and it is the same certificate that went in",
  );

  // A wrong password must say so. Before this, openssl's "Mac verify error" reached the
  // operator unedited, which reads like a corrupt file rather than a typo.
  let msg = "";
  try {
    await readP12(p12, "wrong");
  } catch (err) {
    msg = err instanceof Error ? err.message : "";
  }
  ok(/password/i.test(msg), `a wrong password is reported as a password problem (${msg.slice(0, 48)}…)`);

  let empty = "";
  try {
    await readP12(Buffer.alloc(0), "");
  } catch (err) {
    empty = err instanceof Error ? err.message : "";
  }
  ok(/empty/i.test(empty), "and an empty file is refused before openssl sees it");
}

console.log("\nreading what the certificate says");
if (certPem) {
  const info = certInfoFromPem(certPem);
  // The callsign lives in an unnamed OID. Reading commonName instead — the obvious mistake,
  // and the one PHP's `subject.undefined` invites — would give "Example Operator".
  eq(info.callsign, "K9XYZ", "the callsign comes from the subject OID, not commonName");
  eq(info.name, "Example Operator", "and the name from commonName");
  eq(info.dxcc, 291, "the DXCC entity is read out of extension .1.4");
  eq(info.qsoStart?.toISOString().slice(0, 10), "1945-01-01", "the QSO window opens where the certificate says");
  eq(info.qsoEnd?.toISOString().slice(0, 10), "2030-12-31", "and closes there");
  ok(info.validTo.getTime() > Date.now(), "the certificate's own validity is read separately");

  // The extension value is wrapped in an ASN.1 string inside the OCTET STRING. Cloudlog
  // hands the wrapper to MySQL and lets an INT column strip it; a stray "\x13\x03" here
  // would put `19` in the DXCC field of every upload.
  const raw = certExtensionText(new X509Certificate(certPem).raw, "1.3.6.1.4.1.12348.1.4");
  eq(raw, "291", "with the ASN.1 wrapper stripped rather than left on the front");
  eq(certExtensionText(new X509Certificate(certPem).raw, "1.3.6.1.4.1.99999.1"), null,
     "an absent extension reads as absent, not as garbage");
}

const STATION: LotwStation = {
  callsign: "K9XYZ",
  dxcc: 291,
  grid: "en61",
  state: "wi",
  county: "Kenosha",
  cqZone: 4,
  ituZone: 7,
  iota: null,
  canadian: false,
};

const QSO: LotwContact = {
  callsign: "g3abc",
  band: "20m",
  bandRx: null,
  mode: "FT8",
  freqHz: 14_074_000,
  freqRxHz: null,
  propMode: null,
  satName: null,
  startTime: new Date("2026-08-23T14:30:05Z"),
};

console.log("\nthe frequency string");
eq(mhz(14_074_000), "14.074", "trailing zeros are trimmed");
eq(mhz(14_000_000), "14", "a whole number loses its decimal point entirely");
eq(mhz(7_074_000), "7.074", "40m");
eq(mhz(10_100_000), "10.1", "one decimal place is one decimal place");
eq(mhz(144_200_000), "144.2", "VHF");
// The reason this is not String(hz / 1e6): binary floating point makes some divisions
// print an artefact, and the string goes into the SIGNED BYTES as well as the field.
ok(!mhz(28_074_000).includes("0000000"), "and no floating-point artefact reaches the signature");

console.log("\nthe LoTW mode name");
eq(lotwMode("FT8"), "FT8", "FT8 is its own LoTW mode");
eq(lotwMode("MFSK", "FT4"), "FT4", "and so is FT4, which must not collapse to MFSK");
eq(lotwMode("MFSK", "JS8"), "DATA", "an MFSK submode LoTW does not know becomes DATA");
eq(lotwMode("MFSK"), "DATA", "as does bare MFSK");
eq(lotwMode("PSK", "BPSK31"), "PSK31", "BPSK31 is spelled PSK31 at LoTW");
eq(lotwMode("PSK", "QPSK63"), "PSK63", "and QPSK63 is PSK63");
eq(lotwMode("JT65", "JT65B"), "JT65", "JT65 submodes collapse to the family");
eq(lotwMode("JT9", "JT9G"), "JT9G", "except JT9G, which LoTW keeps");
eq(lotwMode("TOR", "GTOR"), "GTOR", "GTOR is its own mode");
eq(lotwMode("TOR", "AMTOR"), "AMTOR", "while TOR otherwise means AMTOR");
eq(lotwMode("PKT"), "PACKET", "PKT is spelled PACKET");
eq(lotwMode("SSB", "USB"), "SSB", "USB is SSB");
eq(lotwMode("CW"), "CW", "CW is CW");

console.log("\nthe signed string — the part that fails silently if it is wrong");
{
  // GOLDEN. Transcribed from Cloudlog's adif_export.php, which uploads successfully to the
  // live service. The order is alphabetical BY ADIF FIELD NAME — station fields, then
  // contact fields — and it is neither documented by ARRL nor guessable.
  eq(
    signData(STATION, QSO),
    "4EN617KENOSHAWI20MG3ABC14.074FT82026-08-2314:30:05Z",
    "station then contact, alphabetical by field name",
  );

  const s = signData(STATION, QSO);
  // Each of these is a way it has been got wrong or could be. Asserted individually so a
  // regression names the mistake instead of just diffing one long string.
  ok(!s.includes("K9XYZ"), "the STATION callsign is absent — it is not part of the signature");
  ok(!s.includes("291"), "and neither is the station DXCC");
  ok(s.includes("2026-08-23"), "the date carries dashes, not YYYYMMDD");
  ok(s.includes("14:30:05Z"), "the time carries colons and a trailing Z");
  ok(!s.includes(" "), "nothing separates the parts — no spaces");
  ok(!s.includes("EN61-"), "and no separators of any other kind");
  ok(s.indexOf("EN61") < s.indexOf("20M"), "station fields come before contact fields");
  ok(s.indexOf("4") < s.indexOf("EN61"), "CQZ sorts before GRIDSQUARE");
  ok(s.indexOf("KENOSHA") < s.indexOf("WI"), "US_COUNTY sorts before US_STATE");
  ok(s.startsWith("4"), "and with no province, CQZ leads");
}

console.log("\nabsent parts are omitted, not sent empty");
{
  const bare: LotwStation = {
    callsign: "K9XYZ", dxcc: 291, grid: "EN61",
    state: null, county: null, cqZone: null, ituZone: null, iota: null, canadian: false,
  };
  eq(
    signData(bare, { ...QSO, callsign: "VK2XYZ", band: "40M", mode: "FT4",
      freqHz: 7_047_500, startTime: new Date("2026-01-02T03:04:05Z") }),
    "EN6140MVK2XYZ7.0475FT42026-01-0203:04:05Z",
    "a station with only a grid signs only its grid",
  );
  // An empty string would still occupy a position and change every signature. This is the
  // difference between "omitted" and "empty" mattering in bytes rather than in principle.
  ok(!signData(bare, QSO).includes("undefined"), "and nothing leaks a placeholder");
}

console.log("\na Canadian station");
{
  const ca: LotwStation = {
    callsign: "VE3ABC", dxcc: 1, grid: "FN03",
    state: "on", county: null, cqZone: 2, ituZone: 4, iota: null, canadian: true,
  };
  const s = signData(ca, QSO);
  // CA_PROVINCE sorts FIRST, ahead of CQZ. A province sent as US_STATE would sort seventh
  // instead — a valid-looking file with a signature LoTW cannot verify.
  ok(s.startsWith("ON2FN034"), `the province leads, then CQZ, grid, ITUZ (${s.slice(0, 12)})`);
}

console.log("\nthe .tq8 file");
if (certPem && keyPem) {
  const cert = { ...certInfoFromPem(certPem), certPem, keyPem };
  const built = buildTq8(cert, STATION, [QSO]);
  const text = gunzipSync(built.gz).toString("utf8");

  ok(built.gz[0] === 0x1f && built.gz[1] === 0x8b, "it is gzip, whatever the extension suggests");
  ok(text.startsWith("<TQSL_IDENT:"), "and starts with the version banner");
  ok(text.includes("<Rec_Type:5>tCERT"), "carries the certificate record");
  ok(text.includes("<Rec_Type:8>tSTATION"), "the station record");
  ok(text.includes("<Rec_Type:8>tCONTACT"), "and a contact record");
  ok(!text.includes("<?xml"), "no XML anywhere — this is an ADIF-shaped stream");
  ok(!text.includes("BEGIN CERTIFICATE"), "the PEM armour is stripped from the certificate body");
  eq(built.included, 1, "one contact went in");

  // EVERY DECLARED LENGTH MUST MATCH THE BYTES THAT FOLLOW. This is where the two
  // newline-inclusive fields go wrong: CERTIFICATE and SIGN_LOTW_V2.0 count the newline
  // after the value, every other field does not, and a reader that trusts the count —
  // LoTW's does — takes one byte too few off the base64 and fails to verify.
  let checked = 0;
  let bad: string | null = null;
  const re = /<([A-Za-z0-9_.]+):(\d+)(?::\d+)?>/g;
  for (let m = re.exec(text); m; m = re.exec(text)) {
    const declared = Number(m[2]);
    const start = m.index + m[0].length;
    const next = text.indexOf("<", start);
    // Record separators are blank lines, so the gap to the next tag can carry more than one
    // trailing newline. Compare against the value with its trailing newlines stripped.
    const gap = (next < 0 ? text.slice(start) : text.slice(start, next)).replace(/\n+$/, "");
    const actual = Buffer.byteLength(gap, "utf8");
    checked++;
    // Exactly the declared length, or one less for the two fields whose declared length
    // counts the newline that follows the value.
    if (actual !== declared && actual !== declared - 1) {
      bad = `${m[1]} declares ${declared} but ${actual} bytes follow`;
      break;
    }
  }
  ok(bad === null, bad ?? `all ${checked} field lengths agree with their contents`);
  ok(checked > 10, `and there were enough fields to be worth checking (${checked})`);

  // THE SIGNATURE ACTUALLY VERIFIES. Internal consistency only — it proves the bytes in
  // SIGN_LOTW_V2.0 are an RSA-SHA1 signature over the bytes in SIGNDATA under this key. It
  // does NOT prove LoTW agrees those are the right bytes; only the golden strings above
  // speak to that, and only a real upload settles it.
  const sig = /<SIGN_LOTW_V2\.0:\d+:6>([^\n]+)\n/.exec(text)?.[1] ?? "";
  const sd = /<SIGNDATA:\d+>([^\n]+)\n/.exec(text)?.[1] ?? "";
  ok(sig.length > 100, `the signature is present (${sig.length} base64 chars)`);
  eq(sd, signData(STATION, QSO), "and SIGNDATA holds exactly what signData produces");
  ok(
    createVerify("RSA-SHA1")
      .update(sd, "utf8")
      .verify(new X509Certificate(certPem).publicKey, Buffer.from(sig, "base64")),
    "the signature verifies against the certificate's public key",
  );
}

console.log("\ncontacts outside the certificate's QSO window");
if (certPem && keyPem) {
  const cert = { ...certInfoFromPem(certPem), certPem, keyPem };
  const old = { ...QSO, callsign: "W1AW", startTime: new Date("1930-06-01T12:00:00Z") };
  const built = buildTq8(cert, STATION, [QSO, old]);

  // Excluded HERE rather than sent and refused. LoTW rejects the whole file when one record
  // fails and does not say which one, so a single 1930 contact would cost the entire batch.
  eq(built.included, 1, "the contact inside the window goes");
  eq(built.excluded.length, 1, "and the one outside it does not");
  eq(built.excluded[0]?.callsign, "W1AW", "named, so the operator can see which");
  ok(
    (built.excluded[0]?.reason ?? "").includes("1945-01-01"),
    "with the window boundary in the reason rather than just 'skipped'",
  );
  ok(!gunzipSync(built.gz).toString("utf8").includes("W1AW"), "and it is genuinely not in the file");
}

console.log("\nreading LoTW's reply");
{
  // LoTW answers 200 for a refusal as readily as for an acceptance, so the status code says
  // nothing and the marker in the body is the whole signal.
  ok(readLotwReply(200, "<html><!-- .UPL. accepted -->1 out of 1 QSOs added</html>").ok,
     "the accepted marker is success");
  ok(!readLotwReply(200, "<html><!-- .UPL. rejected -->Signature failed</html>").ok,
     "the rejected marker is failure, even at 200");
  ok(readLotwReply(200, "<!-- .UPL. rejected -->Signature failed").detail.includes("Signature failed"),
     "and carries LoTW's own words rather than 'upload failed'");

  // THE ONE THAT MATTERS. A maintenance page is a 200 with neither marker. Read as success
  // it would mark the batch sent and lose those contacts silently — nothing would ever
  // retry them, because the flag says they went.
  const quiet = readLotwReply(200, "<html><body>Logbook of the World is offline for maintenance.</body></html>");
  ok(!quiet.ok, "a 200 with neither marker is NOT success");
  ok(quiet.detail.includes("neither"), "and says so plainly");
  ok(!readLotwReply(500, "").ok, "a 500 is a failure");
  ok(!readLotwReply(200, "").ok, "and so is an empty 200");
  ok(readLotwReply(200, "<script>x</script><!-- .UPL. accepted -->ok").ok,
     "script tags in the page do not defeat the match");
}

console.log("\nthe reply LoTW really sends");
{
  // CAPTURED from the live service on 2026-08-23, trimmed. The whole page is navigation, a
  // sponsor logo and the upload form again, which is why the first 300 characters of its
  // text used to be a menu bar rather than an answer.
  const real =
    "<html><body>Logbook File Upload Today is Sun, 23 Aug 2026 UTC Log On . --&gt; Search " +
    "Help: Search Yaesu | LoTW &reg; Principal Sponsor Logbook File Upload " +
    "File k9xyz-2026-08-23-13-57-11-digishack.tq8 queued for processing. " +
    "Here you can upload a log (.TQ8) or certificate-request (.TQ5) file." +
    "<!-- .UPL. accepted --></body></html>";
  const r = readLotwReply(200, real);
  ok(r.ok, "the real acceptance is read as success");
  ok(
    r.detail.includes("queued for processing"),
    `the log line is the sentence that says so, not the menu bar (${r.detail.slice(0, 48)})`,
  );
  ok(!r.detail.includes("Principal Sponsor"), "the sponsor logo does not end up in the log");
  // QUEUED, not added. LoTW validates afterwards and reports by email, so this reply cannot
  // say how many contacts were kept. An earlier comment in this project claimed it carried
  // an "N out of M records added" count; that is eQSL's behaviour, conflated with this one.
  ok(
    !/\d+ out of \d+/.test(r.detail),
    "and it carries no per-record count, because LoTW does not give one here",
  );
}

console.log("\nreconciling what LoTW actually holds");
{
  // The key is callsign + band + UTC DAY, and the looseness is deliberate. LoTW returns its
  // own normalised ADIF, so a minute-exact or mode-exact comparison would report healthy
  // uploads as missing, clear their flags and upload the log again — turning a safety net
  // into a machine for generating traffic. Over-strict matching has already cost this
  // project once: exact-minute matching rejected 52% of a real eQSL inbox.
  const adif =
    "<PROGRAMID:4>LoTW <EOH>\n" +
    "<CALL:5>G3ABC<BAND:3>20M<MODE:3>FT8<QSO_DATE:8>20260823<TIME_ON:6>143005<EOR>\n" +
    "<CALL:6>VK2XYZ<BAND:3>40M<MODE:3>FT4<QSO_DATE:8>20260102<TIME_ON:6>030405<EOR>\n";
  const keys = keysFromAdif(adif);
  ok(keys.size === 2, `both records are read (${keys.size})`);
  ok(keys.has("G3ABC|20M|2026-08-23"), "callsign, band and day form the key");
  ok(keys.has("VK2XYZ|40M|2026-01-02"), "and the second one too");
  // The minute is NOT in the key: a contact at 14:30 and the same contact reported back at
  // 14:31 have to be the same contact.
  ok(![...keys].some((k) => k.includes("1430")), "the time is not part of the key");
  // Nor the mode, because LoTW maps submodes onto its own list and can name it differently.
  ok(![...keys].some((k) => k.includes("FT8")), "and neither is the mode");
  // A header with no records must not read as "LoTW holds nothing", which would un-mark
  // every recent upload at once. It yields an empty set, and the caller treats a failed
  // fetch as no answer rather than as a negative one.
  ok(keysFromAdif("<PROGRAMID:4>LoTW <EOH>\n").size === 0, "an empty report reads as empty");
}


console.log("\nthe filename");
{
  const n = tq8Filename("K9XYZ", new Date("2026-08-23T14:30:05Z"));
  ok(n.endsWith(".tq8"), `ends in .tq8, which LoTW requires (${n})`);
  ok(n.startsWith("k9xyz-"), "and leads with the callsign");
  ok(!/[^a-z0-9.-]/.test(n), "with nothing in it that needs escaping in a multipart header");
  ok(tq8Filename("VE3ABC/P").startsWith("ve3abc-p-"), "a portable callsign's slash is flattened");
}
}

void main().then(() => {
  rmSync(dir, { recursive: true, force: true });
  console.log(`
${pass} passed, ${fail} failed
`);
  if (fail > 0) process.exit(1);
});
