#!/usr/bin/env bash
#
# DigiShack first-time install.
#
#   ./scripts/install.sh
#
# Idempotent: safe to re-run. Never overwrites an existing .env, and never
# regenerates SETTINGS_KEY once it exists — doing so would make every stored
# credential permanently undecryptable.
#
# Does NOT create a login. The first admin comes from the /setup page, so no
# password ever lands on disk.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

# --- output helpers --------------------------------------------------------
if [ -t 1 ]; then
  R='\033[0;31m'; G='\033[0;32m'; Y='\033[0;33m'; B='\033[1m'; N='\033[0m'
else
  R=''; G=''; Y=''; B=''; N=''
fi
step() { printf "\n${B}==> %s${N}\n" "$1"; }
ok()   { printf "    ${G}ok${N}   %s\n" "$1"; }
warn() { printf "    ${Y}warn${N} %s\n" "$1"; }
die()  { printf "    ${R}fail${N} %s\n" "$1" >&2; exit 1; }

# --- prerequisites --------------------------------------------------------
step "Checking prerequisites"

command -v node >/dev/null 2>&1 || die "node is not installed (need 20 or newer)"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || die "node $NODE_MAJOR is too old — DigiShack needs 20 or newer"
ok "node $(node -v)"

command -v npm >/dev/null 2>&1 || die "npm is not installed"
ok "npm $(npm -v)"

if command -v mysql >/dev/null 2>&1; then
  ok "mysql client present"
else
  warn "no mysql client on PATH — fine if the server is remote"
fi

if command -v openssl >/dev/null 2>&1; then
  ok "openssl present"
else
  warn "openssl missing — falling back to node for key generation"
fi

# --- .env -----------------------------------------------------------------
step "Configuring .env"

gen_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))'
  fi
}

if [ -f .env ]; then
  ok ".env already exists — leaving it alone"

  # Backfill SETTINGS_KEY only if absent. Never replace one: every encrypted
  # setting in the database is tied to it.
  if grep -qE '^\s*SETTINGS_KEY\s*=\s*.+$' .env; then
    ok "SETTINGS_KEY present"
  else
    printf '\n# Master key for encrypted settings (generated by install.sh).\n' >> .env
    printf '# Losing or changing this makes every stored credential undecryptable.\n' >> .env
    printf 'SETTINGS_KEY=%s\n' "$(gen_key)" >> .env
    ok "generated and appended SETTINGS_KEY"
  fi
else
  [ -f .env.example ] || die ".env.example is missing — is this a complete checkout?"
  cp .env.example .env

  KEY="$(gen_key)"
  printf '\n# Master key for encrypted settings (generated by install.sh).\n' >> .env
  printf '# Losing or changing this makes every stored credential undecryptable.\n' >> .env
  printf 'SETTINGS_KEY=%s\n' "$KEY" >> .env

  chmod 600 .env
  ok "created .env from .env.example (mode 600) with a fresh SETTINGS_KEY"
  warn "edit .env and set DATABASE_URL before continuing"
fi

# Refuse to go further against the placeholder credentials.
if grep -qE '^\s*DATABASE_URL\s*=\s*"?mysql://digishack:changeme@' .env; then
  printf "\n${Y}DATABASE_URL is still the example value.${N}\n"
  printf "Edit %s/.env, then re-run this script.\n\n" "$ROOT"
  printf "Create the database first:\n\n"
  cat <<'SQL'
  CREATE DATABASE digishack CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE USER 'digishack'@'localhost' IDENTIFIED BY 'a-real-password';
  GRANT ALL PRIVILEGES ON digishack.* TO 'digishack'@'localhost';
  FLUSH PRIVILEGES;
SQL
  exit 1
fi

# --- dependencies ---------------------------------------------------------
step "Installing dependencies"
if [ -f package-lock.json ]; then
  npm ci
  ok "npm ci"
else
  npm install
  ok "npm install"
fi

# --- database -------------------------------------------------------------
step "Applying database migrations"

# `migrate deploy` rather than `migrate dev`: it never prompts and never resets,
# which is what you want on a machine holding a real log.
if npx prisma migrate deploy; then
  ok "migrations applied"
else
  die "migration failed — check DATABASE_URL and that MySQL is reachable"
fi

# --- build ----------------------------------------------------------------
step "Building"
npm run build
ok "production build complete"

# --- PM2 ------------------------------------------------------------------
step "Process manager"

mkdir -p logs
ok "logs/ ready"

if command -v pm2 >/dev/null 2>&1; then
  if pm2 describe digishack-web >/dev/null 2>&1; then
    pm2 reload ecosystem.config.js --update-env
    ok "reloaded existing PM2 process"
  else
    pm2 start ecosystem.config.js
    ok "started under PM2"
  fi
  pm2 save >/dev/null 2>&1 || warn "pm2 save failed — process list won't survive a reboot"
  printf "\n    Run this once to start PM2 at boot:\n      %s\n" "$(pm2 startup | tail -1)"
else
  warn "pm2 not installed — install with: npm i -g pm2"
  warn "or run in the foreground with: npm start"
fi

# --- done -----------------------------------------------------------------
PORT_VALUE="$(grep -E '^\s*PORT\s*=' .env | tail -1 | cut -d= -f2 | tr -d '" ' || true)"
PORT_VALUE="${PORT_VALUE:-3000}"

printf "\n${G}${B}DigiShack is installed.${N}\n\n"
printf "  1. Open http://localhost:%s — you'll be sent to /setup\n" "$PORT_VALUE"
printf "  2. Create the first admin account there (no password is stored on disk)\n"
printf "  3. Add service credentials under Settings — they're encrypted at rest\n"
printf "  4. Create a station, then start logging\n\n"
printf "  Optional sample data:  npm run db:seed\n"
printf "  Reverse proxy config:  deploy/nginx/digishack.conf\n"
printf "  Upgrade later with:    ./scripts/update.sh\n\n"
